export enum ACCESS_LEVELS {
  LEVEL_5 = 5,
  LEVEL_4 = 4,
  LEVEL_3 = 3,
  LEVEL_2 = 2,
  LEVEL_1 = 1
}

export enum ACTION_ACCESS {
  DISABLE_2FA_USER = 1 << 0,
  ANY_ACTION_USER = 1 << 1,
  BALANCE_CHANGE_USER = 1 << 2,
  WITHDRAWAL_USER = 1 << 3,
  CHANGE_WALLET = 1 << 4,
  DISABLE_2FA_PARTNER = 1 << 5,
  CHANGE_PASSWORD_PARTNER = 1 << 6,
  VIEW_PASSWORD_USER = 1 << 7,
  AUTHORIZE_USER = 1 << 8,
  BALANCE_WITHDRAWAL_USER = 1 << 9,
  ADD_HASH_USER = 1 << 10,
  CHANGE_PASSWORD_USER = 1 << 11,
  APPROVE_PARTNER = 1 << 12,
  PARTNER_WITHDRAWAL_HISTORY = 1 << 13,
  PARTNER_WITHDRAWAL_APPROVE = 1 << 14,
  VIEW_DASHBOARD = 1 << 15,
  VIEW_STATISTICS = 1 << 16,
  VIEW_USERS = 1 << 17,
  VIEW_PARTNERS = 1 << 18,
  VIEW_VERIFICATIONS = 1 << 19,
  VIEW_PAYMENTS = 1 << 20,
  VIEW_PAIRS = 1 << 21,
  VIEW_CONTENT = 1 << 22,
  VIEW_MAILING = 1 << 23,
  VIEW_EXPENSES = 1 << 24,
  VIEW_SECURITY = 1 << 25,
  VIEW_BONUSES = 1 << 26,
  VIEW_SETTINGS = 1 << 27,
  VIEW_NEWS = 1 << 28,
  MANAGE_USER_BAN = 1 << 29,
  MANAGE_USER_DELETION = 1 << 30
}

export const ALLOWED_PERMISSIONS = Object.keys(ACTION_ACCESS).filter(key => isNaN(Number(key)))

export const ACTION_PERMISSIONS: Record<ACTION_ACCESS, ACCESS_LEVELS[]> = {
  // users
  [ACTION_ACCESS.DISABLE_2FA_USER]: [ACCESS_LEVELS.LEVEL_3],
  [ACTION_ACCESS.ANY_ACTION_USER]: [ACCESS_LEVELS.LEVEL_3],
  [ACTION_ACCESS.BALANCE_CHANGE_USER]: [ACCESS_LEVELS.LEVEL_3],
  [ACTION_ACCESS.WITHDRAWAL_USER]: [ACCESS_LEVELS.LEVEL_5],
  [ACTION_ACCESS.CHANGE_WALLET]: [ACCESS_LEVELS.LEVEL_5],
  [ACTION_ACCESS.VIEW_PASSWORD_USER]: [ACCESS_LEVELS.LEVEL_5],
  [ACTION_ACCESS.AUTHORIZE_USER]: [ACCESS_LEVELS.LEVEL_5],
  [ACTION_ACCESS.BALANCE_WITHDRAWAL_USER]: [ACCESS_LEVELS.LEVEL_5],
  [ACTION_ACCESS.ADD_HASH_USER]: [ACCESS_LEVELS.LEVEL_5],
  [ACTION_ACCESS.CHANGE_PASSWORD_USER]: [ACCESS_LEVELS.LEVEL_3],
  [ACTION_ACCESS.MANAGE_USER_BAN]: [ACCESS_LEVELS.LEVEL_3],
  [ACTION_ACCESS.MANAGE_USER_DELETION]: [ACCESS_LEVELS.LEVEL_3],

  // partners
  [ACTION_ACCESS.APPROVE_PARTNER]: [ACCESS_LEVELS.LEVEL_4],
  [ACTION_ACCESS.PARTNER_WITHDRAWAL_HISTORY]: [ACCESS_LEVELS.LEVEL_4],
  [ACTION_ACCESS.PARTNER_WITHDRAWAL_APPROVE]: [ACCESS_LEVELS.LEVEL_4],
  [ACTION_ACCESS.DISABLE_2FA_PARTNER]: [ACCESS_LEVELS.LEVEL_5],
  [ACTION_ACCESS.CHANGE_PASSWORD_PARTNER]: [ACCESS_LEVELS.LEVEL_5],

  // pages
  [ACTION_ACCESS.VIEW_DASHBOARD]: [ACCESS_LEVELS.LEVEL_5],
  [ACTION_ACCESS.VIEW_STATISTICS]: [ACCESS_LEVELS.LEVEL_4],
  [ACTION_ACCESS.VIEW_USERS]: [ACCESS_LEVELS.LEVEL_2],
  [ACTION_ACCESS.VIEW_PARTNERS]: [ACCESS_LEVELS.LEVEL_4],
  [ACTION_ACCESS.VIEW_VERIFICATIONS]: [ACCESS_LEVELS.LEVEL_2],
  [ACTION_ACCESS.VIEW_PAYMENTS]: [ACCESS_LEVELS.LEVEL_3],
  [ACTION_ACCESS.VIEW_PAIRS]: [ACCESS_LEVELS.LEVEL_4],
  [ACTION_ACCESS.VIEW_CONTENT]: [ACCESS_LEVELS.LEVEL_3],
  [ACTION_ACCESS.VIEW_MAILING]: [ACCESS_LEVELS.LEVEL_3],
  [ACTION_ACCESS.VIEW_EXPENSES]: [ACCESS_LEVELS.LEVEL_3],
  [ACTION_ACCESS.VIEW_SECURITY]: [ACCESS_LEVELS.LEVEL_4],
  [ACTION_ACCESS.VIEW_BONUSES]: [ACCESS_LEVELS.LEVEL_4],
  [ACTION_ACCESS.VIEW_SETTINGS]: [ACCESS_LEVELS.LEVEL_4],
  [ACTION_ACCESS.VIEW_NEWS]: [ACCESS_LEVELS.LEVEL_3]
}

export function canPerformAction(
  userAccessLevel: ACCESS_LEVELS,
  permissions: number,
  requiredPermission: ACTION_ACCESS
): boolean {
  return (permissions & requiredPermission) === requiredPermission
}
